services:
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - postgres_test
    environment:
      DATABASE_URL: "postgres://testuser:testpass@postgres_test:5432/testdb?sslmode=disable"
    command: ["go", "test", "./..."]
    profiles:
      - test
  postgres_test:
    extends:
      file: docker-compose.yml
      service: postgres
    restart: always
    container_name: test_postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    profiles:
      - test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      retries: 5
      timeout: 3s
volumes:
  postgres_data: