FROM golang:1.23

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

#ENV DATABASE_URL="postgres://postgres:postgres@postgresql:5432/testdb?sslmode=disable"

CMD ["go", "test", "./..."]
